---
title: "hw_01"
author: "lisa liubovich"
date: "2024-01-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# R Basics

```{r basics 1}
cdi <- read_csv(file = "https://dcgerard.github.io/stat_415_615/data/cdi.csv")
```

```{r basics 2}
cdi <- cdi %>% 
  mutate(log_capita_income = log(capita_income))
```

```{r basics 3}
cdi %>% 
  summarise(mean_area = mean(area),
            sd_are = sd(area))
```

```{r basics 4}
cdi <- cdi %>% 
  rename(population = pop)
```

```{r basics 5}
cdi %>% 
  filter(state == "DE")
```

```{r basics 6}
ggplot(cdi, mapping = aes(x = unemployment, y = capita_income)) +
  geom_point() +
  geom_smooth(method = lm)
```

There seems to be a weak-moderate negative relationship between unemployment and capita_income. The relationship does not fit a linear relationship very well, so a non linear relationship might be more appropriate.

```{r basics 7}
ggplot(cdi, mapping = aes(x = region, y = capita_income)) +
  geom_boxplot()
```

# Misc

let:

```{r}
x <- seq(1, 100, by = 3)
```

```{r misc 1}
sum(log(x))
```

```{r misc 2}
log(sum(x))
```

No, the values are not the same.
