---
title: "lab_01"
author: "lisa liubovich"
date: "2024-01-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
```

```{r 1}
cdi <- read_csv(file = "./week_1/cdi.csv")
```

```{r 2}
glimpse(cdi)
```

```{r 3}
cdi %>% 
  summarise(mean = sum(pop),
            sd = sd(pop))
```

```{r 4}
cdi <- cdi %>% 
  mutate(pop = pop/100000)

cdi
```

```{r 5}
ggplot(cdi, mapping = aes(x = log(pop), y = log(physicians))) +
  geom_point()
```

```{r 6}
ggplot(cdi, mapping = aes(x = region, y = log(pop))) +
  geom_boxplot()
```

```{r 7}
ggplot(cdi, mapping = aes(x = log(pop), y = log(physicians))) +
  geom_point() +
  facet_grid(~ region)
```

```{r 8}
cdi_w <- cdi %>% 
  filter(region == "W")

cdi_NC <- cdi %>% 
  filter(region == "NC")

cdi_S <- cdi %>% 
  filter(region == "S")

cdi_NE <- cdi %>% 
  filter(region == "NE")


cdi_w
cdi_NE
cdi_S
cdi_NC
```

9.  

10. It was the best of times,

11. it was the worst of times,

    -   **it was the age of wisdom,**
    -   *it was the age of foolishness,*
    -   [it was the epoch of belief](https://www.youtube.com/watch?v=dQw4w9WgXcQ) ...
